/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.devagri3.view;

import br.com.devagri3.dao.Conecta;
import java.awt.event.KeyEvent;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
/**
 *
 * @author Willyan
 */
public class frmLogin extends javax.swing.JFrame {
    static String logado ="";
    Connection con = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    
    
 
    
    public frmLogin() throws ClassNotFoundException {
        
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        //con = 
        con = Conecta.conectabd();
        getRootPane().setDefaultButton(botao_entrar);
    }
    
  //=======================METODO LOGAR===============================
  
  //TO FIX COLOCAR NO DAO
    public static String getLogado(){
        return logado;
    }
    
    public void Logar(){
    String sql = "Select * from usuario where nome = ? and senha = ? ";
    
   
    try {
        
        pst = con.prepareStatement(sql);
        pst.setString(1, jtfUser.getText());
        pst.setString(2, jtfSenha.getText());
        
        rs = pst.executeQuery();
        
        
        if (rs.next()){
            logado=jtfUser.getText();
            
            String passa_logado = "Insert into usuario logado values ?";
            System.out.println("Bem vindo "+logado);
            
            frmPrincipal frm = new frmPrincipal();
            frm.setVisible(true);
            this.dispose();
        } 
         else
        {
            JOptionPane.showMessageDialog(null, "Usuário e/ou Senha Inválidos");
        }
    } 
    catch(SQLException error)
    {
    JOptionPane.showMessageDialog(null, error);
   }
  } 
  //=======================FIM METODO LOGAR===========================
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtfUser = new javax.swing.JTextField();
        jtfSenha = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        botao_entrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Bem Vindo");
        setMaximumSize(new java.awt.Dimension(760, 470));
        setMinimumSize(new java.awt.Dimension(760, 470));
        setResizable(false);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtfUser.setBackground(new java.awt.Color(242, 244, 243));
        jtfUser.setBorder(null);
        getContentPane().add(jtfUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 240, 120, 20));

        jtfSenha.setBackground(new java.awt.Color(242, 242, 242));
        jtfSenha.setBorder(null);
        jtfSenha.setRequestFocusEnabled(false);
        jtfSenha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfSenhaKeyPressed(evt);
            }
        });
        getContentPane().add(jtfSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 240, 120, 20));

        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 120, 90, 230));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/devagri3/assets/frmLogin.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, 470));

        botao_entrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_entrarActionPerformed(evt);
            }
        });
        getContentPane().add(botao_entrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 420, -1, 10));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        Logar();
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jtfSenhaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfSenhaKeyPressed

        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
           Logar();
        }
        
        if (evt.getKeyCode() == KeyEvent.VK_ESCAPE) {
            this.dispose();
       }
    }//GEN-LAST:event_jtfSenhaKeyPressed

    private void botao_entrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_entrarActionPerformed
        Logar();
    }//GEN-LAST:event_botao_entrarActionPerformed

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_formKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                try {
                    new frmLogin().setVisible(true);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(frmLogin.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botao_entrar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPasswordField jtfSenha;
    private javax.swing.JTextField jtfUser;
    // End of variables declaration//GEN-END:variables
}
